OnboardingVC 버튼 액션 구현
iOS-PPAK/PPAK_CVS pull request #10
Opened 2022-10-01 12:04 UTC by minji0801

## Features ✨
Onboarding 화면에서 버튼 액션을 구현했습니다.

## Screenshots 📸
https://user-images.githubusercontent.com/49383370/193408565-9ff557e1-ffed-4689-acf5-07e2a8b69e08.mp4

## To Reviewers
- HomeVC로 화면 전환될 때 더 부드러운 효과를 내기 위해서 animated를 true로 변경했습니다.
- 페이지 컨트롤이 넘어갈 때 Lottie 이미지와 텍스트가 바로 바뀌는 부분은 다음 작업인 효과 적용에서 개선하도록 하겠습니다.

2022-10-02 05:23 UTC, eung7 approved these changes
개인적으로 애니메이션이 들어가 고급진 느낌이 마음에 듭니다
👍👍👍

2022-10-02 05:23 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Onboarding/OnboardingVC.swift
> +  @objc private func swipeAction(_ gesture: UIGestureRecognizer) {
objc method를 사용하는 것도 방법이지만, 이벤트 처리의 통일성을 위해서
Swipe Action 처리도
RxGesture라는 라이브러리를 통해 컨트롤 할 수 있다고 알고 있어요.
그것도 다음 회의때 사용 유무에 대해 논의 해봐요 ~!

2022-10-03 02:53 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Onboarding/OnboardingVC.swift
> +  @objc private func swipeAction(_ gesture: UIGestureRecognizer) {
저도 해당 부분에 대해 한 번 알아보긴 했는데 확실히 RxGesture 라이브러리 사용하면 코드가 간결해지긴 하더라구요. 사용하는 데 있어서는 찬성입니다

2022-10-03 07:50 UTC, WhiteHyun requested changes

2022-10-03 07:50 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Onboarding/OnboardingVC.swift
> +  }
화면전환과 관련된 건 Coordinator에게 위임해주세요

---

그리고 밑의 코드에서는 coordinator에게 화면전환을 요청해주세요.
https://github.com/iOS-PPAK/PPAK_CVS/blob/ac110a70965596bcc0f24f2a66107f6ec3cbc4d2/PPAK_CVS/Sources/Scenes/Onboarding/OnboardingVC.swift#L142

https://github.com/iOS-PPAK/PPAK_CVS/blob/ac110a70965596bcc0f24f2a66107f6ec3cbc4d2/PPAK_CVS/Sources/Scenes/Onboarding/OnboardingVC.swift#L149

2022-10-03 12:10 UTC, isGeekCode approved these changes

2022-10-05 13:45 UTC, minji0801 commented on PPAK_CVS/Sources/Scenes/Onboarding/OnboardingVC.swift
> +  }
`currentPage`를 ViewModel에서 관리하고 싶은데 마땅한 방법이 떠오르지 않습니다ㅠ

2022-10-06 00:58 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Onboarding/OnboardingVC.swift
> +  }
currentPage를 ViewModel의 Output으로 설정하면 될 것 같습니다.
밑의 코드 한번 참고해주시고
보완해야할 점이나 궁금하신 점은 코멘트 남겨주세요 !! 

```Swift
enum SwipeDirection {
  case left
  case right
}
```

VC 

```Swift
class OnboardingViewController { 

 func bind() {

  // -------------------------------
  // ------------INPUT--------------
  // -------------------------------
  
  // 다음버튼 클릭
  self.nextButton.rx.tap
    .bind(to: viewModel.input.nextButtonEvent)
    .disposed(by: disposeBag)

  // 스와이프 반응
  self.view.rx
    .swipeGesture([.left, .right])
    .when(.recognized)
    .subscribe(onNext: { [weak self] gesture in
      guard let self = self else { return }

      switch gesture.direction {
      case .left:
        viewModel.input.swipeGesture2.onNext(.left)
      case .right:
        viewModel.input.swipeGesture2.onNext(.right)
      default:
        break
      }
    })
    .disposed(by: disposeBag)
  
  // -------------------------------
  // ------------OUTPUT-------------
  // -------------------------------

  // CurrentPage가 변화할때마다 여기서 작업 수행
  viewModel.output.currentPage
    .bind(onNext: {
      print("updated currnetPage")
    })

}
```

ViewModel 
 
```Swift
class OnboardingViewModel { 

  struct Input {
    let swipeGestureDetector = PublishSubject<SwipeDirection>()
    let nextButtonEvent = PublishSubject<Void>()
  }
  
  struct Output {
    let currentPage = BehaviorRelay<Int>(value: 0)
    let navigateToHomeVC = PublishSubject<Void>() // 이건 어떤 역할을 하는지 잘 모르겠어서 일단 여기에 넣었습니다 ! 
  }

  let disposeBag = DisposeBag()
  let input = Input()
  let output = Output()

  // 현재 페이지를 저장하는 Computed Property (그냥 참조하기 쉽게 만든 것, 굳이 이렇게 할 필요는 없긴 합니다 ~)
  var currentPage: Int { return output.currentPage.value }

  func bind() {

    input.nextButtonEvent
      .bind { [weak self] in
        guard let self = self else { return }
        if self.currentPage == 2 {
          self.output.navigateToHomeVC(self.navigationController ?? UINavigationController())
        } else {
          let updatedPage = self.currentPage + 1
          self.output.currentPage.accept(updatedPage)
        }
      }

    input.swipeGestureDetector
      .map { [weak self] direction in
        guard let self = self else { return }
        switch direction {
        case .right:
          if self.currentPage > 0 {
            let updatedPage = self.currentPage - 1
            self.output.currentPage.accept(updatedPage)
          }
        case .left:
          if self.currentPage < 2 {
            let updatedPage = self.currentPage + 1
            self.output.currentPage.accept(updatedPage)
          }
        }
      }
}
```

2022-10-06 02:08 UTC, WhiteHyun requested changes
ViewModel에서 Coordinator를 생성하는 것이 아닌 Coordinator가 직접적으로 화면전환을 실행하면 됩니다.

만약 ViewModel에서 진행하려면 viewModel에서 coordinator를 갖고 있어야할 듯 싶습니다.

2022-10-13 12:52 UTC, WhiteHyun approved these changes

2022-10-13 12:52 UTC, merged