[BUG] NavigationController PopGesture 버그 수정
iOS-PPAK/PPAK_CVS pull request #101
Opened 2023-02-26 11:55 UTC by eung7

## Features ✨

1. `NavigationController`의 `BookmarkVC`의 `PopGesture`가 제대로 작동하지 않은 버그를 수정했습니다.

> 원인
```swift
// BaseViewController.swift

  override func viewDidLoad() { // ❌
    navigationController?.interactivePopGestureRecognizer?.delegate = self
  }
```

- `viewDidLoad`에 위 코드를 작성하면 다른 `VC`에서 `Pop`이 되고 되돌아오면 `delegate`가 현재 VC를 받지 못 해서 아래의 메서드가 불려지지 않습니다.

```swift
extension BaseViewController: UIGestureRecognizerDelegate {
  func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
    return navigationController?.viewControllers.count ?? 0 > 1
  }
}
```

> 해결
- viewWillAppear의 코드를 옮겨 구현했습니다.

```swift
  override func viewWillAppear(_ animated: Bool) { // 🟢
    navigationController?.interactivePopGestureRecognizer?.delegate = self
  }
```

---

2. `Pagination`을 할 때 맨 아래 `LoadingCell`을 의도적으로 `1초 delay`시키는 오퍼레이터를 삭제했습니다.

--- 

3. Bookmark에서 찜한 상품을 선택하고 찜을 해제하고 다시 돌아오면 update가 되지 않은 것을 새로 구현했습니다.

---

## Screenshots 📸

https://user-images.githubusercontent.com/97531269/221407627-aec24f6b-59c2-4ef4-acf4-2dd415b58e09.mp4

## To Reviewers

2023-02-26 14:22 UTC, WhiteHyun requested changes

2023-02-26 14:22 UTC, WhiteHyun commented on PPAK_CVS/Configuration/Base/BaseViewController.swift
>    }
super 코드 꼭 넣어주세요!

2023-02-26 14:26 UTC, WhiteHyun commented
base branch를 release로 변경하겠습니다!

2023-02-26 15:10 UTC, WhiteHyun approved these changes
고생하셨습니다 ☺️

2023-02-26 15:20 UTC, minji0801 approved these changes

2023-02-27 12:33 UTC, isGeekCode approved these changes

2023-02-27 12:33 UTC, isGeekCode commented
고생하셨습니다~

2023-02-27 12:34 UTC, merged