Feat/home vc/touch event
iOS-PPAK/PPAK_CVS pull request #13
Opened 2022-10-06 14:28 UTC by eung7

## Features ✨
1. PageControl Delegate -> BehaviorRelay 인덱스 감지 변경
3. 두 개의 Dropdown 이벤트 감지 기능 구현
4. Header에 있는 드롭다운들을 VC.view에 addSubview
5. 빈 공간 터치할 때 드롭다운 사라짐 구현
6. 편의점 드롭다운 요소 클릭 시 현재 선택된 편의점 로고 이미지로 변경 이벤트 구현 

## Screenshots 📸
![Simulator Screen Recording - iPhone 14 Pro - 2022-10-06 at 23 25 15](https://user-images.githubusercontent.com/97531269/194339358-e1620240-e9c7-435f-8045-5e70cece6323.gif)

## To Reviewere

enum 구조체는 임시로 만든 것입니다.

수정한 게 조금 많습니다.
만들었던 Custom UIView 객체들의 이벤트를 
모두 RxSwift를 이용한 이벤트 플로우로 수정하였습니다. 

그 외에 드롭다운 관련한 것들이 많습니다!

2022-10-08 02:19 UTC, WhiteHyun requested changes
## 반드시 알아야할 사항 ⛔️

### 1. 커밋 크기가 너무 큽니다.

커밋을 하는 이유는 코드를 추적함에 따라 코드리뷰 뿐 아니라 잘못된 코드를 바로고치는데 용이하기 때문입니다. 첫 번째 커밋처럼 PR크기만큼의 코드를 하나의 커밋으로 뭉텅 넣어버리시면 리뷰하는 입장으로서는 난감합니다. 😭 코드 읽는 게 너무 힘들어요.

### 2. PR을 더 작게 만들어서 올려주세요.

PR 하나에 너무 여러가지 기능을 구현하셨습니다.
1. 로고버튼에 이미지를 넣어 적용시킨 것
2. 다양한 로고를 누르면 거기에 맞춰 UI를 변경시킨 것
3. 홈 화면을 누르면 띄워진 뷰가 드롭다운되어 `hidden`처리 되는 것
4. UIPageControl의 처리 방식을 리뉴얼한 것

등 해당 부분을 각 PR로 만들어서 적용하시는 것이 바람직합니다. 지금과 같은 PR을 처리하는 데 들이는 비용이 너무 많이 들어요 ㅜ

## P.S.

라이브러리 추가한 것도 꼭!! 얘기해주셨으면 좋겠습니다. Minji님 브랜치에서도 RxGesture를 넣으셨는데, 서로 충돌 일어나는 건 아닐지.. 무섭네요 😅

2022-10-08 02:19 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Common/CVSDropdownView.swift
> +  private lazy var ministopButton = createLogoButton("logo_ministop")
`imageName.rawValue`로 변경 안하셨네요

2022-10-08 02:19 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Common/FilterDropdownView.swift
>    lazy var stackView = UIStackView().then {
private 붙이시면 성능향상에 도움이 될 거 같아요!

2022-10-08 02:19 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Common/PageControl.swift
> +//  }
만약 사용하지 않는 부분이면 지워주세요

2022-10-08 02:19 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Common/PageControl.swift
> +    let oneplusLabel = labels[1]
`oneplusLabel` -> `onePlusLabel`로 수정하는 것이 옳은 것 같습니다.

2022-10-08 02:19 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Common/CVSDropdownView.swift
> +    case .all: return "lgoo_all"
오타 있네요. "logo_all"로 바꿔주셔야할 거 같아요

2022-10-08 02:19 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Common/CVSDropdownView.swift
> +enum CVSDropdownCase {
CollectionHeaderView에서도 사용되는 만큼 독립적인 파일로 만드는 게 좋을 거 같아요.

2022-10-08 02:19 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Common/CVSDropdownView.swift
>    private func setupLayout() {
여러 UI를 vertical하게 배치하는 거면 `UIStackView`가 레이아웃을 놓기에도 효율적인데, `StackView`를 사용하지 않은 이유를 여쭤봐도 될까요?

2022-10-08 02:19 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Home/HomeCollectionHeaderView.swift
> +    $0.setImage(UIImage(named: "logo_all"), for: .normal)
CVSDropdownCase의 `imageName`을 이용하면 좋을 거 같아요.

2022-10-08 11:39 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Common/CVSDropdownView.swift
> +  private lazy var ministopButton = createLogoButton("logo_ministop")
수정완료 했습니다 ! 
참고로 이 부분은 나중에 긱코드님이 데이터 모델 구현해주시면 
그걸로 수정할 생각입니다 ~!

2022-10-08 11:39 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Common/FilterDropdownView.swift
>    lazy var stackView = UIStackView().then {
수정완료 했습니다 !

2022-10-08 11:39 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Common/PageControl.swift
> +//  }
수정완료 했습니다 !

2022-10-08 11:40 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Common/PageControl.swift
> +    let oneplusLabel = labels[1]
수정완료 했습니다 !

2022-10-08 11:40 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Home/HomeCollectionHeaderView.swift
> +    $0.setImage(UIImage(named: "logo_all"), for: .normal)
수정완료 했습니다 !

2022-10-08 11:40 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Common/CVSDropdownView.swift
>    private func setupLayout() {
너무 급하게 구현하는 바람에 거기까지 생각을 못했던것 같아요 ..
스택뷰로 수정완료 했습니다!

2022-10-08 11:41 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Common/CVSDropdownView.swift
> +enum CVSDropdownCase {
이것도 마찬가지로
긱코드님이 구현해준 데이터모델로 사용할 계획이라서 일단 보류하는게 나을까요 ?

2022-10-08 11:41 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Common/CVSDropdownView.swift
> +    case .all: return "lgoo_all"
수정완료 했습니다 !

2022-10-08 11:44 UTC, eung7 commented
asdf

2022-10-08 11:45 UTC, eung7 commented
맞아요.. 저도 이것저것 하다보니까 정신을 차려보니 너무 많은 것들을 구현하고 있었네요 .. 
앞으로는 작성해주신 것들 잘 지키고 주의하도록 하겠습니다 ! 

RxGesture관련해서는 merge할 떄 RxGesture를 삭제한 상태로 푸쉬하는 게 나을까요 ?

2022-10-10 10:30 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Common/CVSDropdownView.swift
> +enum CVSDropdownCase {
그대로 사용하시고, 나중에 GeekCode님이 구현하시면 그 때 수정해서 PR 올려주시면 될 거 같아요. 혹시 더 좋은 방법이 있다면 의견 주세요!

2022-10-10 10:34 UTC, WhiteHyun approved these changes

2022-10-10 12:58 UTC, minji0801 approved these changes

2022-10-10 13:01 UTC, isGeekCode approved these changes

2022-10-10 13:27 UTC, merged