Enum 생성, TitleLogoView생성
iOS-PPAK/PPAK_CVS pull request #14
Opened 2022-10-10 08:15 UTC by isGeekCode

## Features ✨

- Enum 생성하였고 머지한 다음 폰트컬러, 이미지 수정예정입니다.
- 편의점 이름 로고로 사용할 View클래스 생성하였습니다

2022-10-10 10:28 UTC, WhiteHyun requested changes
아래만 고쳐주시면 바로 approve 할게요!

1. xcodeproj도 커밋해주세요. 파일 인식을 못합니다 ㅜ
2. 저희 indent는 `4`가 아닌 `2`입니다. 맞춰주세요.

2022-10-10 11:36 UTC, isGeekCode commented
네 수정했습니다!!

2022-10-10 12:02 UTC, eung7 approved these changes
👍👍👍👍

2022-10-10 12:37 UTC, minji0801 approved these changes

2022-10-10 13:45 UTC, isGeekCode commented
수정 했습니다 ~ 리뷰 부탁드립니다!

2022-10-10 13:46 UTC, isGeekCode commented
This branch has conflicts that must be resolved
```
PPAK_CVS.xcodeproj/project.pbxproj
```

2022-10-10 13:46 UTC, isGeekCode commented
```
PPAK_CVS.xcodeproj/project.pbxproj
```
이 파일이 충돌한다고 나오는데 괜찮을까요???

2022-10-10 13:49 UTC, minji0801 commented
<img width="505" alt="Screen Shot 2022-10-10 at 10 48 44 PM" src="https://user-images.githubusercontent.com/49383370/194881352-04d7c3fb-020c-4373-b838-9f3485e8d2be.png">

이거 다 포함하면 되는 건가요?

2022-10-11 12:35 UTC, WhiteHyun requested changes

2022-10-11 12:35 UTC, WhiteHyun commented on PPAK_CVS/Configuration/Constants/Enum/EventType.swift
> +}
다시 한 번 확인해주세요

2022-10-11 12:35 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Common/TitleLogoView.swift
> +  }
backgroundColor도 적용해야하지 않을까요??

2022-10-20 11:06 UTC, isGeekCode commented on PPAK_CVS/Configuration/Constants/Enum/EventType.swift
> +}
이거 인덴트를 수정하는 것 말씀하시는걸까요?

2022-10-20 11:12 UTC, isGeekCode commented on PPAK_CVS/Configuration/Constants/Enum/EventType.swift
> +}
아 케이스 이름이 안맞군요 수정했습니다!

2022-10-20 11:16 UTC, isGeekCode commented on PPAK_CVS/Sources/Scenes/Common/TitleLogoView.swift
> +  }
수정했습니다!

2022-10-20 12:09 UTC, WhiteHyun approved these changes

2022-10-20 12:15 UTC, merged