Feat/common/uiextension
iOS-PPAK/PPAK_CVS pull request #23
Opened 2022-10-20 11:03 UTC by isGeekCode

홈화면 색상코드를 추가했습니다.

2022-10-20 12:07 UTC, eung7 approved these changes

2022-10-20 12:22 UTC, WhiteHyun requested changes

2022-10-20 12:22 UTC, WhiteHyun commented on PPAK_CVS/Configuration/Extensions/UIColor+.swift
> +    if (cString.count) != 6 {
괄호 지워주세요!

2022-10-20 14:16 UTC, WhiteHyun reviewed
## 적극적으로 고려해주세요

- UIColor 내부에 `Type Method`로 `UIColor`를 리턴하는 것 보다는 init을 생성하는 게 적절하다고 생각합니다.
- RGB와 RGBA를 나누는 것 보다, alpha에 `default value`를 주어 하나의 initializer로 만드는 게 방향성에 맞다고 생각합니다.
- `convertFromHex` 역시 initializer로 처리해주시는 게 맞다고 봅니다!
-  `convertFromHex`의 파라미터명이 hexValue이지만 타입은 String입니다. `Int` 타입으로 바꾸어 처리하는 건 어떨까요? 그러면 <kbd>#</kbd> 기호체크도 안해도 되고 Scanner 처리도 하지 않아도 되니 간결해지겠네요 👍🏼 
- `convertFromHex`의 코드 중 6자리가 아니면 기본값을 gray로 리턴하셨는데, 이 역시 nil로 리턴하여 개발자에게 코드가 잘못되었음을 알리는 게 코드 방향성에 맞다고 생각합니다.

2022-10-21 05:23 UTC, isGeekCode commented
@WhiteHyun  곰곰히 생각해봤는데 HEX코드에 숫자가 들어가야할것같다고 하셨는데
16진수는 10이 올 차례부터 abcd가 들어가서 HEX에는 String이 변수로 들어가야하지않을까요!??ㅠ  어제 말씀하신걸 제가 잘못 이해한것인지!!
혹시 다시한번 말씀해주실 수 있을까요

2022-10-22 01:51 UTC, WhiteHyun commented
> @WhiteHyun 곰곰히 생각해봤는데 HEX코드에 숫자가 들어가야할것같다고 하셨는데 16진수는 10이 올 차례부터 abcd가 들어가서 HEX에는 String이 변수로 들어가야하지않을까요!??ㅠ 어제 말씀하신걸 제가 잘못 이해한것인지!! 혹시 다시한번 말씀해주실 수 있을까요

2진수, 8진수, 16진수는 접두어를 통해서 표기할 수 있습니다.

> 2진수: 0b0101
> 8진수: 0o7125
> 16진수: 0xFA12

따라서 16진수를 정수형으로 표기할 수 있습니다.

```swift
let fifteen: Int = 0xF

let whiteHexadecimal: UInt = 0xFFFFFF
```

제가 Int로 처리하는 것을 권해드린 이유는 String으로 처리했을 때의 오버헤드를 Int가 줄일 수 있기 때문입니다.
String으로 받게 되면, 그 값이 16진수로 들어온 것이 맞는지, 이상한 값이 들어오진 않았는지, 접두어가 \#이 들어있는지 안들어있는지, 등 여러 조건처리를 해야하지만, Int로 받게되는 경우에는 단지 0x000000 ~ 0xFFFFFF 사이의 값인지만 체크하면 되니까요. ☺️

2022-10-30 06:52 UTC, minji0801 approved these changes

2022-11-03 12:30 UTC, WhiteHyun approved these changes

2022-11-03 12:31 UTC, merged