Refactor/bookmark scenes with ReactorKit & 화면전환 구현
iOS-PPAK/PPAK_CVS pull request #28
Opened 2022-11-01 06:38 UTC by eung7

## Features ✨

+ BookmarkVC 를 ReactorKit으로 리팩토링 하였습니다.
+ HomeVC <-> BookmarkVC 간 화면전환을 구현하였습니다.

## Screenshots 📸

## To Reviewers

+ @WhiteHyun 님이 사용하신 화면전환 할 때 여러번의 클릭을 방지하는 로직을 참고했습니다.
+ Coordinator 내부 코드는 제가 처음 짜보는 거라서 이상한 부분이 있으면 꼭 코멘트 남겨주세요!
+ 화면 전환 할 때 ViewModel에서 State를 Void로 받는 방법은 없을까요..? 그냥 이벤트를 받기만 해도 되는 Flow도 Bool으로 설정해줘야 하니 불편한 감이 없지 않아 있네요..

2022-11-02 06:33 UTC, WhiteHyun requested changes
1. Bookmark 페이지에서 gesture 기능이 누락되어있습니다. 혹시 스와이프로 `Home`을 못 가게 일부로 막아두신 건가요?
2. 혹시 NavigationBar를 Custom으로 구현해볼 생각은 없으신가요?

2022-11-02 06:33 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Bookmark/BookmarkCoordinator.swift
> +        finish(childCoordinator: self)
```suggestion
        self.parentCoordinator?.finish(childCoordinator: self)
```

2022-11-02 06:33 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Home/HomeVC.swift
> +
공백 제거해주세요! 빌드 하시면 사라질 거에요.

2022-11-02 06:33 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Bookmark/BookmarkViewModel.swift
> +final class BookmarkViewModel: ViewModel {
너무 일대일 대응이 되어있는 거 같아요. 반복적이고 같은 역할을 하는 녀석들을 하나로 묶어서 쓰는 게 좋을 거 같아요.

2022-11-02 06:33 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Home/HomeCoordinator.swift
> +        coordinator.start(childCoordinator: coordinator)
```suggestion
        self.start(childCoordinator: coordinator)
```

2022-11-02 06:35 UTC, WhiteHyun requested changes

2022-11-02 06:35 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Bookmark/BookmarkVC.swift
> +      .disposed(by: disposeBag)
화면전환은 Coordinator에게 위임해야해요.

2022-11-02 07:28 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Bookmark/BookmarkCoordinator.swift
> +        finish(childCoordinator: self)
```swift
navigationController?.interactivePopGestureRecognizer?.delegate = nil
```
해당 코드를 작성하여 Swipe Back이 가능하도록 했습니다.
이 문제를 해결해도 NavigationBar를 커스텀 해야할까요..?

2022-11-02 11:07 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Home/HomeCoordinator.swift
> +        coordinator.start(childCoordinator: coordinator)
아 이런 로직이었군요!!
수정완료입니다.

2022-11-02 11:14 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Bookmark/BookmarkVC.swift
> +      .disposed(by: disposeBag)
```swift
    // BookmarkVC -> HomeVC
    viewModel.state
      .map { $0.showHomeVC }
      .filter { $0 }
      .bind(onNext: { [unowned self] _ in
        self.toHomeVC()
      })
      .disposed(by: disposeBag)
  }

  func toHomeVC() {
    self.navigationController.popViewController(animated: true)
    parentCoordinator?.finish(childCoordinator: self)
  }
```

이 코드들은 BookmarkCoordinator입니다. 
이렇게 구현하면 될까요?

2022-11-02 11:15 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Bookmark/BookmarkViewModel.swift
> +final class BookmarkViewModel: ViewModel {
HomeVM과 BookmarkVM의 역할이 너무 겹친다는 말씀이신가요..?
조금 더 정확한 설명 부탁드립니다!

2022-11-02 11:28 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Bookmark/BookmarkVC.swift
> +      .disposed(by: disposeBag)
죄송합니다 코디네이터 구현 전에 깜빡하고 안 지운 것 같아요!

2022-11-02 14:50 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Bookmark/BookmarkVC.swift
> +      .disposed(by: disposeBag)
죄송할 필요는 없어요..ㅋㅋㅋㅋㅋㅋ

2022-11-02 16:49 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Bookmark/BookmarkViewModel.swift
> +final class BookmarkViewModel: ViewModel {
아 아닙니다 무시하셔도 돼요

2022-11-03 12:33 UTC, isGeekCode approved these changes

2022-11-03 12:38 UTC, minji0801 approved these changes

2022-11-03 12:40 UTC, WhiteHyun approved these changes

2022-11-03 12:40 UTC, merged