Feat/reactive background color
iOS-PPAK/PPAK_CVS pull request #40
Opened 2022-11-12 10:29 UTC by eung7

## Features ✨

+ 편의점 드롭다운에서 새로운 항목을 선택하면 배경 색깔이 바뀌는 로직을 구현했습니다.

## Screenshots 📸

https://user-images.githubusercontent.com/97531269/201469930-d559257d-418a-4fc4-9394-5998a177ec44.mov

## To Reviewers

+ 수정해야할 부분 있으면 코멘트 남겨주세요!

2022-11-12 11:02 UTC, WhiteHyun requested changes
이런 식으로 적용하면 어떨까 싶네요.
```swift
enum DropdownType {
  case cvs(CVSType)
  case setting

  var image: UIImage? {
    switch self {
    case .cvs(let type):
      return type.image
    case .setting:
      return UIImage(named: "setting")
    }
  }
}
```

2022-11-12 11:02 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Bookmark/BookmarkViewModel.swift
> +      }
DropdownCase를 리팩토링하셔서 적용시키셔야할 것 같네요. 코드가 중복돼요!

2022-11-12 11:02 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Home/HomeViewModel.swift
> +      }
요기도 수정하셔야할 것 같네요

2022-11-12 12:09 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Bookmark/BookmarkViewModel.swift
> +      }
수정완료했습니다! 한번 확인해주세요~

2022-11-12 12:09 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Home/HomeViewModel.swift
> +      }
수정완료했습니다! 한번 확인해주세요~

2022-11-13 13:00 UTC, WhiteHyun requested changes
`build`해서 공백 제거해주세요!

2022-11-13 13:00 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Common/CVSDropdownView.swift
> +  private lazy var ministopButton = createLogoButton(CVSDropdownCase.cvs(.all).image)
연관값 잘못 적용하신 거 같아요!

2022-11-13 13:00 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Home/HomeViewModel.swift
> +      var newCvsType: CVSType?
CVS 대문자로 해주실 수 있나요??

2022-11-16 22:49 UTC, isGeekCode approved these changes

2022-11-17 00:52 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Common/CVSDropdownView.swift
> +  private lazy var ministopButton = createLogoButton(CVSDropdownCase.cvs(.all).image)
수정완료했습니다!

2022-11-17 00:52 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Home/HomeViewModel.swift
> +      var newCvsType: CVSType?
수정완료했습니다!

2022-11-17 00:55 UTC, WhiteHyun approved these changes

2022-11-17 12:07 UTC, minji0801 approved these changes

2022-11-17 12:12 UTC, merged