네트워크 끊겼을 때 처리했습니다
iOS-PPAK/PPAK_CVS pull request #41
Opened 2022-11-14 12:07 UTC by minji0801

## Features ✨
네트워크가 끊기면 아래 화면을 보여주도록 구현했습니다.

## Screenshots 📸
<img src="https://user-images.githubusercontent.com/49383370/201654380-79d37f42-ed3c-4262-941f-f104199bce0d.jpeg" width="300">

## To Reviewers
네트워크 연결이 안 되면 아래 코드처럼 NetworkViewController를 RootViewController로 보여주도록 했는데요.
이 부분도 Coordinator로 구현해야 할지 잘 몰라서 일단 이렇게 작성해 보았습니다.
```swift
  DispatchQueue.main.async {
    let networkViewController = NetworkViewController()
    networkViewController.modalPresentationStyle = .fullScreen
    UIApplication.shared.windows.first?.rootViewController?.show(networkViewController, sender: nil)
  }
```

2022-11-14 13:24 UTC, WhiteHyun commented
종료버튼을 구현하려 앱을 끄게 만든 의도가 무엇인가요?

2022-11-14 14:11 UTC, minji0801 commented
> 종료버튼을 구현하려 앱을 끄게 만든 의도가 무엇인가요?

음.. 네트워크 연결을 필수로 가정하고 구현해서 그렇습니다.! 혹시 필수가 아닌가요?

2022-11-15 03:37 UTC, WhiteHyun commented
> 음.. 네트워크 연결을 필수로 가정하고 구현해서 그렇습니다.! 혹시 필수가 아닌가요?

네트워크 연결은 필수이긴 하지만, 종료버튼으로 앱을 종료시키려는 의도가 궁금했어요. 대부분의 앱은 사용자에게 알려주고, 종료버튼은 제공하지 않아서요.

2022-11-17 12:15 UTC, minji0801 commented
> > 음.. 네트워크 연결을 필수로 가정하고 구현해서 그렇습니다.! 혹시 필수가 아닌가요?
> 
> 네트워크 연결은 필수이긴 하지만, 종료버튼으로 앱을 종료시키려는 의도가 궁금했어요. 대부분의 앱은 사용자에게 알려주고, 종료버튼은 제공하지 않아서요.

아 생각해보니 그렇네요 😅
오늘 스터디 시간에 응칠님께서 주신 아이디어인데요 아래 이미지처럼 변경해보려고 합니다! 수정해서 다시 요청드리겠습니다~
![Screen Shot 2022-11-17 at 9 04 09 PM](https://user-images.githubusercontent.com/49383370/202443550-7176c4a6-8ba2-4abf-8429-26d02a90cdf8.png)

2022-11-17 12:26 UTC, eung7 requested changes

2022-11-17 12:26 UTC, eung7 commented on PPAK_CVS/Sources/Managers/NetworkCheck.swift
> +}
삭제요청!

2022-11-17 12:26 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Network/NetworkVC.swift
> +}
삭제요청!

2022-11-21 12:36 UTC, eung7 approved these changes

2022-11-21 12:37 UTC, isGeekCode approved these changes

2022-11-25 10:01 UTC, WhiteHyun commented on PPAK_CVS/Configuration/Extensions/UIApplication+.swift
> +  }
1. `class`로 재정의가능하게 한 이유가 궁금하네요. 따로 재정의해서 사용해야할 경우가 있을까요?
2. `keyWindow`는 이미 `ios 13.0`버전에서 **`deprecated`** 되었기에 다른 방법으로 구현하는 게 좋을 거 같아요. 예를 들면, 이런 식인거죠!
 ```suggestion
  var topViewController: UIViewController? {
    (connectedScenes.first as? UIWindowScene)?.windows.first?.rootViewController
  }
```
제가 이렇게 구현한 이유는  `ios 13`부터 UIApplication의 keyWindow가 `deprecated`되는 대신 `connectedScenes` 프로퍼티로 `window`에 접근이 가능하도록 바뀌었고, `windows: [UIWindow]`프로퍼티의 첫 번째는 SceneDelegate에 구현되어있는 `window`이므로 `first` 프로퍼티로 window에 접근하여 가져오도록 구현했습니다.

> Reference
>
> 1. [[iOS] 13 이슈 대응 및 변경 사항 공유](https://jinnify.tistory.com/63)
> 2. [Reference to currently active window](https://developer.apple.com/forums/thread/695115)

2022-11-27 11:04 UTC, minji0801 commented on PPAK_CVS/Configuration/Extensions/UIApplication+.swift
> +  }
> 1. `class`로 재정의가능하게 한 이유가 궁금하네요. 따로 재정의해서 사용해야할 경우가 있을까요?
> 2. `keyWindow`는 이미 `ios 13.0`버전에서 **`deprecated`** 되었기에 다른 방법으로 구현하는 게 좋을 거 같아요. 예를 들면, 이런 식인거죠!
> 
> 제가 이렇게 구현한 이유는 `ios 13`부터 UIApplication의 keyWindow가 `deprecated`되는 대신 `connectedScenes` 프로퍼티로 `window`에 접근이 가능하도록 바뀌었고, `windows: [UIWindow]`프로퍼티의 첫 번째는 SceneDelegate에 구현되어있는 `window`이므로 `first` 프로퍼티로 window에 접근하여 가져오도록 구현했습니다.
> 
> > Reference
> > 
> > 1. [[iOS] 13 이슈 대응 및 변경 사항 공유](https://jinnify.tistory.com/63)
> > 2. [Reference to currently active window](https://developer.apple.com/forums/thread/695115)

1. `UIAppliation.topViewController()`로 사용하기 위해서는 클래스 함수로 만들어야 했습니다.
2. 오 그렇군요! 덕분에 `connectedScenes`을 알게 되었습니다👍 적어주신 코드와 여러 블로그들 참고하면서 아래와 같이 수정했는데 어떠신가요??
```swift
  // 변수로 선언
  private var topVC: UIViewController? {
    let scenes = UIApplication.shared.connectedScenes
    let windowScene = scenes.first as? UIWindowScene
    let window = windowScene?.windows.first
    return window?.rootViewController
  }
  ...
  // 사용할 때
  guard let topVC = self.topVC else { return }
```

2022-11-27 11:05 UTC, WhiteHyun commented on PPAK_CVS/Configuration/Extensions/UIApplication+.swift
> +  }
최고에요!

2022-11-28 12:15 UTC, WhiteHyun approved these changes

2022-11-28 12:48 UTC, merged