Feat/setting vc UI
iOS-PPAK/PPAK_CVS pull request #46
Opened 2022-12-05 09:37 UTC by isGeekCode

## Features ✨
- SettingViewController 화면구현
- SettingTableView 구현
- SettingTableViewCell 구현
- 버전정보를 가져오는 함수 구현
- 칸별 AccessoryType 분기처리
- Extension: NSAttributedString+ 추가

## Screenshots 📸
<img width="415" alt="스크린샷 2022-12-05 오후 6 24 16" src="https://user-images.githubusercontent.com/76529148/205602966-68069b9f-15dd-4cc6-9db2-e527aa03f9bd.png">

## To Reviewers
브랜치 커밋이 커져서 먼저 머지하려고 합니다.
남은 작업은 아래 순서대로 진행할 예정입니다.
색상은 구역확인을 위해 들어가있습니다.
네비게이션 바 구현 시점에서 삭제예정입니다.

남은 작업
- 네비게이션바
- Coordinator
- 셀의 세부내역

NSAttributedString 익스텐션에 구현한 withLineSpacing()은 자간을 조절하는 함수입니다. 버전정보에 사용하였습니다.

2022-12-05 10:11 UTC, eung7 commented on PPAK_CVS/SettingTableViewCell.swift
> +  }
필요하지 않은 메서드는 지우는 게 좋을 것 같아요!

2022-12-05 10:12 UTC, eung7 requested changes
확인해주세요!

2022-12-05 10:25 UTC, eung7 requested changes

2022-12-05 10:25 UTC, eung7 commented on PPAK_CVS/SettingTableViewCell.swift
> +  }
사용하지 않은 메서드는 지우는 게 좋을 것 같아요!

2022-12-05 10:25 UTC, eung7 commented on PPAK_CVS/SettingTableViewCell.swift
> +}
```swift
extension String {} 
```
을 통해서 Cell 파일과 분리할 수 있을 것 같아요 !

2022-12-05 10:25 UTC, eung7 commented on PPAK_CVS/SettingTableViewCell.swift
> +  private let titleList = ["알림", "공지사항", "리뷰 남기기", "문의하기", "개발자 응원하기", "버전정보"]
이 Data들은 SettingViewModel에 배치하는게 좋을 것 같아요!
아직 ViewModel이 만들어지지 않아서 그런건가요?

2022-12-05 10:25 UTC, eung7 commented on PPAK_CVS/Sources/Scenes/Setting/SettingVC.swift
> +  }
아직 사용하지 않는 메서드는 지워주셔도 좋을 것 같아요 !

2022-12-05 11:18 UTC, WhiteHyun requested changes

2022-12-05 11:18 UTC, WhiteHyun commented on PPAK_CVS/SettingTableViewCell.swift
> +class SettingTableViewCell: UITableViewCell {
`final` keyword

2022-12-05 11:18 UTC, WhiteHyun commented on PPAK_CVS/SettingTableViewCell.swift
> +import Then
```suggestion
import UIKit

import SnapKit
import Then
```

2022-12-05 11:18 UTC, WhiteHyun commented on PPAK_CVS/SettingTableViewCell.swift
> +    }
불필요한 forEach네용

2022-12-05 11:18 UTC, WhiteHyun commented on PPAK_CVS/SettingTableViewCell.swift
> +    }
`make`로 변경해주세요

2022-12-05 11:18 UTC, WhiteHyun commented on PPAK_CVS/SettingTableViewCell.swift
> +    guard let appVersion = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String else { return ""}
```suggestion
    guard let appVersion = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String else { return "" }
```

2022-12-05 11:18 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Setting/SettingVC.swift
> +
빈줄 제거

2022-12-05 11:18 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Setting/SettingVC.swift
> +  }()
`then` 사용해주세요

2022-12-05 11:18 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Setting/SettingVC.swift
> +    }
`make`로 바꿔주세용

2022-12-05 11:18 UTC, WhiteHyun commented on PPAK_CVS/SettingTableViewCell.swift
> +    addSubview(containerView)
contentView에 넣어야하지 않을까여

2022-12-05 11:18 UTC, WhiteHyun commented on PPAK_CVS/Configuration/Extensions/NSAttributedString+.swift
> +}
얘는 어떠한 작업을 맡고있나요?

2022-12-05 11:18 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Setting/SettingVC.swift
> +class SettingViewController: BaseViewController {
`final` 사용해주세요

2022-12-05 11:18 UTC, WhiteHyun commented on PPAK_CVS/SettingTableViewCell.swift
> +    setupConstraints()
`init`할 때 layout과 constraint를 설정하는 게 낫지 않을까요?

2022-12-05 12:07 UTC, minji0801 approved these changes

2022-12-06 14:44 UTC, isGeekCode commented on PPAK_CVS/SettingTableViewCell.swift
> +}
Instance member 'setTextSpacing' cannot be used on type 'String'; did you mean to use a value of this type instead?

위 에러 메세지가 발생합니다. String안에 구현할 수 없고, 또 NSAttributedString 에도 구현할 수 가 없다고 하여 유지해야할 듯합니다 혹시 또 다른 방법이 없을까요

2022-12-06 14:46 UTC, isGeekCode commented on PPAK_CVS/Sources/Scenes/Setting/SettingVC.swift
> +  }
수정했습니다!

2022-12-06 14:48 UTC, isGeekCode commented on PPAK_CVS/SettingTableViewCell.swift
> +import Then
아 이부분은 한줄 띄어야하는 거군요

2022-12-06 14:51 UTC, isGeekCode commented on PPAK_CVS/SettingTableViewCell.swift
> +  private let titleList = ["알림", "공지사항", "리뷰 남기기", "문의하기", "개발자 응원하기", "버전정보"]
네 이건 ViewModel 생성후 분리하도록 하겠습니다!

2022-12-06 14:52 UTC, isGeekCode commented on PPAK_CVS/SettingTableViewCell.swift
> +class SettingTableViewCell: UITableViewCell {
수정했습니다!

2022-12-06 14:53 UTC, isGeekCode commented on PPAK_CVS/SettingTableViewCell.swift
> +    }
아하. 이건 $0을 깔끔하게 생각하시는 듯 하여 이렇게 한건데 그러면 변수명으로 수정하겠습니다

2022-12-06 14:54 UTC, isGeekCode commented on PPAK_CVS/SettingTableViewCell.swift
> +  }
수정했습니다!

2022-12-06 14:54 UTC, isGeekCode commented on PPAK_CVS/SettingTableViewCell.swift
> +    }
수정했습니다

2022-12-06 14:57 UTC, isGeekCode commented on PPAK_CVS/SettingTableViewCell.swift
> +    }
수정했습니다!

2022-12-06 14:58 UTC, isGeekCode commented on PPAK_CVS/SettingTableViewCell.swift
> +    guard let appVersion = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String else { return ""}
수정했습니다!

2022-12-06 14:58 UTC, isGeekCode commented on PPAK_CVS/Sources/Scenes/Setting/SettingVC.swift
> +    }
수정했습니다!

2022-12-06 14:59 UTC, isGeekCode commented on PPAK_CVS/SettingTableViewCell.swift
> +    addSubview(containerView)
containerView를 contentView로 변수 네이밍을 수정하자는 말씀이실까요

아니면 containerView를 contentView 안에 넣자는 말씀이실까요!!

2022-12-06 15:02 UTC, isGeekCode commented on PPAK_CVS/Configuration/Extensions/NSAttributedString+.swift
> +}
네 SettingTableVIewCell  마지막에 구현된 함수인 `setTextSpacing`를 보시면 아래와 같습니다.
```swift
  private func setTextSpacing(text: String) -> NSAttributedString {
    let introduction = NSAttributedString(string: text).withLineSpacing(100)
    return introduction
  }
```
NSAttributedString값으로 파싱된 String 값에 `원하는  글자간격을 세팅하는 함수`입니다.

2022-12-06 15:03 UTC, isGeekCode commented on PPAK_CVS/Configuration/Extensions/NSAttributedString+.swift
> +}
주석 추가로 커밋했습니다!

2022-12-06 15:04 UTC, isGeekCode commented on PPAK_CVS/Sources/Scenes/Setting/SettingVC.swift
> +class SettingViewController: BaseViewController {
수정했습니다

2022-12-06 15:19 UTC, isGeekCode commented on PPAK_CVS/SettingTableViewCell.swift
> +    setupConstraints()
@WhiteHyun 님께서 원하시는건 Convinience init()에 넣어서 사용하는 걸까요?
저는 SetUI(row)를 TableView Delegate에서 함께 구현하는게 나을것 같아서 이곳에 해봤습니다.

init()에다가 구현하면 그걸 먼저 하고 TableView Delegate의 Cell.setUI(row)함수가 실행될 수 있을까요

2022-12-06 15:36 UTC, isGeekCode commented on PPAK_CVS/Sources/Scenes/Setting/SettingVC.swift
> +
SettingVC, SettingTableViewCell 모든 빈줄 제거했습니다

2022-12-06 15:39 UTC, isGeekCode commented on PPAK_CVS/Sources/Scenes/Setting/SettingVC.swift
> +  }()
then 세팅했습니다

2022-12-09 06:48 UTC, WhiteHyun requested changes

2022-12-09 06:48 UTC, WhiteHyun commented on PPAK_CVS/SettingTableViewCell.swift
> +    setupConstraints()
제 생각에는 Cell이 **`초기화`** 되었을 때, Cell의 전반적인 View Setting이 되어야하는 게  맞다고 생각해서 드린 말씀이었습니다. 지금은 셀이 적어서 reuse되지 않겠지만, 스크롤 가능한 셀이면 연속으로 layout과 constraint 작업을 중복하여 적용시키기 때문에 차후에 버그가 일어날 가능성이 높은 코드입니다. 수정이 필요해보여요.

2022-12-09 06:48 UTC, WhiteHyun commented on PPAK_CVS/SettingTableViewCell.swift
> +    addSubview(containerView)
후자입니다

2022-12-09 06:48 UTC, WhiteHyun commented on PPAK_CVS/SettingTableViewCell.swift
> +}
저도 @eung7 님 의견에 동의합니다! extension으로 빼는 게 더 좋은 거 같아요.
그리고 뺄 때 그대로 함수 붙여넣으시지 마시구 약간만 수정하면 적용되니 한 번 시도해보세요!

2022-12-09 06:52 UTC, WhiteHyun commented on PPAK_CVS/Sources/Scenes/Setting/SettingVC.swift
> +extension SettingViewController: UITableViewDataSource, UITableViewDelegate {
MARK 주석 수정해야할 거 같아요. 그리고 사이에 빈 줄 넣어주세요!


https://github.com/StyleShare/swift-style-guide#%EB%B9%88-%EC%A4%84

2022-12-15 10:23 UTC, isGeekCode commented on PPAK_CVS/Sources/Scenes/Setting/SettingVC.swift
> +extension SettingViewController: UITableViewDataSource, UITableViewDelegate {
수정했습니다!

2022-12-15 10:51 UTC, isGeekCode commented on PPAK_CVS/SettingTableViewCell.swift
> +}
수정하다보니  해당 함수가 단순히 형변환하고 있고 , spacing을 조절하기 위한 함수가 들어가있는 2가지의 기능을 하고 있었습니다. 그래서 형변환 자체는 함수로 빼는 것 자체가 불필요하다고 판단되어 아래와 같이 수정했습니다.

```
let attributeString = NSAttributedString(string: versionString).withLineSpacing(100)
```

2022-12-15 10:59 UTC, isGeekCode commented on PPAK_CVS/SettingTableViewCell.swift
> +    addSubview(containerView)
contentView.addSubView(containerView)로 수정처리했습니다

2022-12-15 12:01 UTC, eung7 approved these changes

2022-12-15 12:28 UTC, isGeekCode commented on PPAK_CVS/SettingTableViewCell.swift
> +    setupConstraints()
init으로 이동처리했습니다

2022-12-15 13:15 UTC, WhiteHyun approved these changes

2022-12-15 13:18 UTC, merged